# 部署《买房记》到GitHub Pages的工作流
name: Deploy static content to Pages

on:
  # 当main分支有推送时触发
  push:
    branches: ["main"]
  # 允许手动触发
  workflow_dispatch:

# 设置GITHUB_TOKEN的权限
permissions:
  contents: read
  pages: write
  id-token: write

# 只允许一个部署同时进行
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # 单一部署工作
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
      - name: 设置Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      - name: 安装依赖
        run: npm ci
      - name: 构建项目
        run: npm run build
      - name: 创建404页面（处理路由）
        run: cp dist/index.html dist/404.html
      - name: 设置Pages
        uses: actions/configure-pages@v4
      - name: 上传构建产物
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'
      - name: 部署到GitHub Pages
        id: deployment
<<<<<<< HEAD
        uses: actions/deploy-pages@v4
=======
        uses: actions/deploy-pages@v3
>>>>>>> 2299704116045599825e5b2fe3e97f81f2a8cc38
